"""empty message

Revision ID: 6857d2b7b307
Revises: 197daa0e22c9
Create Date: 2021-04-25 20:25:19.798802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6857d2b7b307'
down_revision = '197daa0e22c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cargo_capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_class', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crew', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passengers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consumables', mysql.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
