"""empty message

Revision ID: 885d23165d85
Revises: fba939373df7
Create Date: 2021-04-16 01:46:26.060648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '885d23165d85'
down_revision = 'fba939373df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('hair_color', sa.String(length=40), nullable=True),
    sa.Column('eye_color', sa.String(length=40), nullable=True),
    sa.Column('birth_year', sa.String(length=40), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('skin_color', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=40), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('planets', 'surface_water')
    op.drop_column('planets', 'gravity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('gravity', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('planets', sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('vehicles')
    op.drop_table('people')
    # ### end Alembic commands ###
