"""empty message

Revision ID: daed9d0a8e5e
Revises: 6857d2b7b307
Create Date: 2021-04-26 00:06:51.454345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daed9d0a8e5e'
down_revision = '6857d2b7b307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
